### ISSUE TITLE
Make track_identifier the primary key or a unique column

### ISSUE THREAD

**Issue by HumanoidSandvichDispenser** [JackDyre/spotify-file-storage#32]
Make the track_identifier column either the primary key or a unique column in the database for faster look-up time.

**Comment by JackDyre** [comment]
Do you mean a separate table in the db? It already is its own column

**Comment by HumanoidSandvichDispenser** [comment]
I meant when you create the table, instead of

```sql
CREATE TABLE IF NOT EXISTS _13bit_ids (
                    binary TEXT PRIMARY KEY,
                    track_id TEXT,
                    track_identifier TEXT
)
```

you can make the track_identifier unique by adding `UNIQUE` at the end of the column name


```sql
CREATE TABLE IF NOT EXISTS _13bit_ids (
                    binary TEXT PRIMARY KEY,
                    track_id TEXT,
                    track_identifier TEXT UNIQUE
)
```

**Comment by JackDyre** [comment]
What does that do?

Should I also do it for the track_id since it is also unique?

**Comment by HumanoidSandvichDispenser** [comment]
It creates an index, which lets the database directly look up by the column value instead of traversing through each record and comparing the column values.

It's like if your table was a dictionary, then creating an index would create a copy of the dictionary, but instead of the binary representation being the key, the identifier is instead the key. This way, you can directly index by the track_identifier than running a query through all 8000 rows until it finds a matching identifier.

I think it doesn't really matter for track_id because I believe you're only creating and populating the database once, which is important because the tradeoff of indexes is that writes would be slower. But otherwise, you normally would only create an index for track_id or make track_id unique if you are frequently querying against the track_id.

**Comment by JackDyre** [comment]
Makes sense

Will implement this when I get around to implementing the 2^16 track IDs

**Comment by JackDyre** [comment]
Implemented

310f170
